era build-c.log
put console output to file build-c.log [system]
;
date
;
; Build Z80 version
c -o -v c309-9.c
;
; Now build Z280 version
;
; First a Z280 version using the Z80 LIBC.C (runs on Z80)
c309-9 -o -v -ec280z80.com -dZ280 c309-9.c
;
; and the Z280 optimized version from it (only runs on a Z280)
c280z80 -of2 -v -ec280-9.com c309-9.c
;
c280-9 -o2 -v optimh.c
;
dir c*.com [fu
dir optimh.com [fu
;
; Done
put console to console
